### ISSUE TITLE
 Found 552 templates with syntax error

### ISSUE THREAD

**Issue by ZeroJL7** [ExpLangcn/NucleiTP#2]
放入templates文件夹后，nuclei导入tem报错，请问一下怎么解决
![nuclei](https://user-images.githubusercontent.com/100654953/224256891-4dd4a49c-10be-4b5f-a4c6-4755da3332e3.PNG)

**Comment by ExpLangcn** [comment]
Nuclei我记得有个忽略错误模版的参数
